#!/usr/bin/env bash
# script that will display information about subdomains.

function sub_info {
	 if [[ -z "$2" ]] ; then
	    wwwip="$(dig "www.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n')"
	    lb01ip="$(dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n')"
	    web01ip="$(dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n')"
	    web02ip="$(dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n')"
	    wwwrec="$(dig "www.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')"
	    lb01rec="$(dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')"
	    web01rec="$(dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')"
	    web02rec="$(dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')"
	    echo "The subdomain www is a $wwwrec record and point to $wwwip"
	    echo "The subdomain lb-01 is a $lb01rec record and point to $lb01ip"
	    echo "The subdomain web-01 is a $web01rec record and point to $web01ip"
	    echo "The subdomain web-02 is a $web02rec  record and pont to $web02ip"
	 elif [[ "$2" ]] ; then
	     sub="$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $1}' | tr -d '\n;' | cut -d '.' -f1)"
	     rec="$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')"
	     ip="$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n')"
	     echo "The subdomain $sub is a $rec record and points to $ip"
	 fi
}

sub_info "$1" "$2"
