#!/usr/bin/bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80

apt-get -y update
apt-get -y install ngnix
ufw allow 'Nginx HTTP'
echo 'Holberton school' > /var/www/html/index.nginx-debian.html
service nginx start