#!/usr/bin/bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y install ngnix
sudo echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo service nginx start
