#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get -y update
apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get install haproxy=1.8.\*
printf "\n\nfrontend fe_main\n\tmode http\n\tbind *:80\n\tdefault_backend be_main\n\nbackend be_main\n\tmode http\n\tbalance roundrobin\n\tserver 718-web-01 35.231.100.106\n\tserver 718-web-02 35.237.151.115" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start