#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get install haproxy
sudo chown $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend http_front
    bind *:80
    mode http
    default_backend http_back
backend http_back
    balance roundrobin
    server 1550-web-01 34.75.68.113:80 check
    server 1550-web-02 54.226.84.62:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
