#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get -y update
apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get install haproxy=1.8.\*
cp /etc/haproxy/haproxy.cfg .
cat >> /etc/haproxy/haproxy.cfg << EOF
frontend http_front
	bind *:80
	mode http
	default_backend http_back
backend http_back
    balance roundrobin
    server 1550-web-01 34.75.68.113:80 check
    server 1550-web-02 54.226.84.62:80 check
EOF
service haproxy restart
