#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet.
apt-get -y update
apt-get -y install nginx
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
