#!/usr/bin/env bash
# script that:
#   Creates the file /var/run/holbertonscript.pid containing its PID
#   Displays To infinity and beyond indefinitely
#   Displays I hate the kill command when receiving a SIGTERM signal
#   Displays Y U no love me?! when receiving a SIGINT signal
#   Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

sudo touch /var/run/holbertonscript.pid
sudo bash -c "pgrep pid > /var/run/holbertonscript.pid"

function sigterm {
    echo "I hate the kill command"
    sudo rm /var/run/holbertonscript.pid
    exit
}
function sigint {
    echo "Y U no love me?!"
    exit
}
function sigquit {
    sudo rm /var/run/holbertonscript.pid
    exit
}

trap sigterm SIGTERM
trap sigint SIGINT
trap sigquit SIGQUIT

i=1
while [ $i -eq 1 ];
do
    echo "To infinity and beyond"
done
