#!/usr/bin/env bash
# script that displays:
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

i=1

trap "echo I am invincible!!!" SIGTERM
while [ $i -eq 1 ];
do
    echo "To infinity and beyond"
    sleep 2
done
