#!/usr/bin/env bash
# script that gives you information about the holbertonschool file

f="holbertonschool"
if [ ! -e $f ];
then
    echo "holbertonschool file does not exist"
else
    echo "holbertonschool file exists"

    if [ ! -s $f ];
    then
	echo "holbertonschool file is empty"
    else
	echo "holbertonschool file is not empty"
    fi

    if [ ! -d $f ];
    then
	echo "holbertonschool is a regular file"
    fi
fi
